//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintAgentRF.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion
    {
        public long id { get; set; }
        public string nombreagente { get; set; }
        public string contrasenarf { get; set; }
        public string ipequipo { get; set; }
        public Nullable<long> puerto { get; set; }
        public string hostps { get; set; }
    }
}
