//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintAgentRF.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class impresion
    {
        public long id { get; set; }
        public string json { get; set; }
        public Nullable<long> tipoplantilla { get; set; }
        public Nullable<long> estado { get; set; }
    
        public virtual estados estados { get; set; }
        public virtual plantilla plantilla { get; set; }
    }
}
