//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintAgentRF.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plantilla()
        {
            this.impresion = new HashSet<impresion>();
        }
    
        public long id { get; set; }
        public string json { get; set; }
        public Nullable<System.DateTime> ultimaimportacion { get; set; }
        public string plantilla1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<impresion> impresion { get; set; }
    }
}
