//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintAgentRF.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajosterminados
    {
        public long id { get; set; }
        public Nullable<long> impresora { get; set; }
        public Nullable<long> cedula { get; set; }
        public Nullable<System.DateTime> fechahora { get; set; }
    
        public virtual impresoras impresoras { get; set; }
    }
}
